log:
  disable_sentry: true
  level: debug

listener:
  addr: :8000

rpc:
  url:

ws:
  url:

listen:
  chain:
  from_tx: ""
  program_id:

broadcaster:
  addr: ""
  sender_account: ""

core:
  addr:

cosmos:
  addr:

subscriber:
  min_retry_period:
  max_retry_period: