log:
  disable_sentry: true
  level: debug

db:
  url: "postgres://solana:solana@localhost:5432/solana?sslmode=disable"

listener:
  addr: :8000

rpc:
  url: https://api.devnet.solana.com

ws:
  url: wss://api.devnet.solana.com

listen:
  from_tx: d68YSkgCZsp6x4cpz8NotkhkRSGQmnPVAyDRPXpMr8ysSK2XuB1UeqKQsDdn55nfK38iknJUreRs9regNjxe33F
  disable_catchup: false
  program_id: CqnDZ8hyRgaXdeZ9X4Exz9LzMEMipi1sTweXRXyoJHpS

